<?php 
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

$basePath = $this->basePath();
$this->headLink()->appendStylesheet($basePath . '/css/style.css');

$this->headLink(array(
            'rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $basePath . '/images/favicon.ico',
        ));

// HTML5 shim, for IE6-8 support of HTML elements
$this->headScript()->appendFile($basePath . '/js/html5.js', 'text/javascript', 
    array('conditional' => 'lt IE9',));

echo $this->doctype();
?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 Skeleton Application') ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    
    <!-- Scripts -->
    <?php echo $this->headScript() ?>

  </head>

  <body>

    <!-- nav -->
    <nav>
      <ul>
        <li><a class="brand" href="<?php echo $this->url('home') ?>">Home</a></li>
      </ul>
    </nav>

    <article>
      <?php echo $this->content; ?>
    </article> <!-- /container -->

    <footer>
      <p>&copy; <?php echo date('Y'); ?> Joe Balancio. All rights reserved.</p>
    </footer>

  </body>
</html>
